# Generated by Django 6.1 on 2026-09-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
