# Generated by Django 6.1 on 2026-09-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ended_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
